export const metadata: Metadata = {
  title: 'MERN AUTH APP',
  description: 'Generated by create next app',
}
import type { Metadata } from 'next'

// "use client";
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import ReduxProvider from '@/redux/provider'
import { useDispatch } from 'react-redux'
import { AppDispatch } from '@/redux/store'
import React from 'react'
import { logIn, logOut } from '@/redux/features/auth-slice'
const inter = Inter({ subsets: ['latin'] })



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


 
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fullpage">
        <ReduxProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </ReduxProvider>
        </div>
      </body>
    </html>
  )
}
